import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SideMenu from "../components/SideMenu";
import Header from "../components/Header";

export default function Home() {
  const [list_machine, setlist_machine] = useState([]);
  const get_machine = () => {
    fetch("http://192.168.153.144:8000/api/create_machine/", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((response) => response.json())
      .then((jsonresponse) => {
        console.log(jsonresponse);
        setlist_machine(jsonresponse["listado de maquinas"]);
      });
  };
  useEffect(() => {
    get_machine();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>IOT EIA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header></Header>
        <SideMenu></SideMenu>

        <div className={styles.container_machine}>
          {list_machine.map((item, index) => {
            return <div key={"list" + String(index)}>{item.machine_name}</div>;
          })}
        </div>
      </main>
    </div>
  );
}
